### ISSUE TITLE
Front-end framework choice?

### ISSUE THREAD

**Issue by Forge-Media** [Forge-Media/Forge-TSM#4]
Need to choose a front-end framework?
- [x] Bootstrap (stock) - [bootstrap](https://github.com/twbs/bootstrap) 
- [ ] Bootstrap (themed)
- [x] Angular - [angular-ui/bootstrap](https://github.com/angular-ui/bootstrap)
- [ ] Angular 2

**Comment by Forge-Media** [comment]
Um we need to work on connecting the Front end and Back end. Not 100% sure how far you've gotten with the front end, but as far as the back end is concerned we are ready for a Beta version.

**Comment by ShaamzFGN** [comment]
Wow, I only saw this email now. Please contact me on admin@shaamiel.co.za
as I am trying to stray away from gmail. I have created a new github
account which I'm using strictly for FGN projects. Spoke to Marc regarding
the issues, will pull some code and see how we go from there. Please let me
know how much each admin is paying to have our license.

Thanks

Shamz

On Fri, Feb 12, 2016 at 3:40 AM, Jeremy Paton notifications@github.com
wrote:

> Um we need to work on connecting the Front end and Back end. Not 100% sure
> how far you've gotten with the front end, but as far as the back end is
> concerned we are ready for a Beta version.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Forge-Media/Forge-TSM/issues/4#issuecomment-183144648
> .

## 

Shaamiel Goordeen
Information Technology
South Africa ZA
Partnered with http://www.forgegaming.net/hosting/vps/
